version: "3"
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  server:
    build: "./"
    ports:
      - "8080:8080"
    links:
      - "clickhouse"
    depends_on:
      - "clickhouse"
